### ISSUE TITLE
WUT....?

### ISSUE THREAD

**Issue by 3dpowers** [yellows8/3ds_webkithax#3]
can you please make a guide on how to correctly install this HAX
cuz its very confusing

**Comment by yellows8** [comment]
Just touch the slider in the manner specified in the README, that's all(if you have /boot.3dsx setup already ofc).

**Comment by 3dpowers** [comment]
where is that?
i cant find it

**Comment by 3dpowers** [comment]
also does that go in the root of the sd

**Comment by yellows8** [comment]
............ http://yls8.mtheall.com/3dsbrowserhax.php

**Comment by 3dpowers** [comment]
nvm i found the files ill report with the results

**Comment by 3dpowers** [comment]
nothing
happened ...what do you mean by "ofc"

**Comment by 3dpowers** [comment]
do i need a payload

**Comment by yellows8** [comment]
"nothing happened" <- Be more specific.

**Comment by 3dpowers** [comment]
it closed out and said to restart

**Comment by yellows8** [comment]
Just keep retrying until it works without crashing like that.

**Comment by 3dpowers** [comment]
the boot.3dsx is in the root i used the starter kit

**Comment by 3dpowers** [comment]
do i restart though

**Comment by yellows8** [comment]
No, just keep relaunching the browser each time it crashes.

**Comment by 3dpowers** [comment]
ok
where should i try clicking

**Comment by 3dpowers** [comment]
any tips or tricks

**Comment by 3dpowers** [comment]
do i need a payload

**Comment by profi200** [comment]
Can't you read? Just keep trying. It is unstable. You don't need anything except the starter kit from here https://smealum.github.io/3ds/

**Comment by 3dpowers** [comment]
ok

**Comment by yellows8** [comment]
Indeed... READMEs....

**Comment by 3dpowers** [comment]
why does clicking far right on the slider make a diffrence?

**Comment by profi200** [comment]
No idea. We used it internally for a long time and the best success rate was with doing it like this.

**Comment by 3dpowers** [comment]
i need my super accurate pointy stylus

**Comment by 3dpowers** [comment]
how do i know it worked

**Comment by profi200** [comment]
...if it boots into the Homebrew launcher.

**Comment by 3dpowers** [comment]
ok

**Comment by 3dpowers** [comment]
still going

**Comment by 3dpowers** [comment]
usual amount of tries?

**Comment by profi200** [comment]
Max 10. Usually 1-3.

This is not a chat just to remind you.

**Comment by 3dpowers** [comment]
ive been doing this for like 20 min

**Comment by profi200** [comment]
Clear your cookies and reset the browser in the settings.

**Comment by 3dpowers** [comment]
ok

**Comment by 3dpowers** [comment]
mmmmmm cookies

**Comment by 3dpowers** [comment]
how?

**Comment by profi200** [comment]
Quick picture i found on google: http://i.ytimg.com/vi/FU9mVrQUibA/maxresdefault.jpg

The wrench icon.

**Comment by 3dpowers** [comment]
ok

**Comment by 3dpowers** [comment]
omg yellow and grey

**Comment by 3dpowers** [comment]
it worked

**Comment by 3dpowers** [comment]
....

**Comment by 3dpowers** [comment]
face tracking demo just is a black screen

**Comment by profi200** [comment]
It does not work on old 3DS. New 3DS only.

**Comment by 3dpowers** [comment]
how do i exit it then....!

**Comment by 3dpowers** [comment]
there
rebooted

**Comment by 3dpowers** [comment]
whre can i find gb gba gbc emus and bios and other homebrews

**Comment by 3dpowers** [comment]
whats yeti 3ds?

**Comment by 3dpowers** [comment]
oh its like doom

**Comment by profi200** [comment]
This is not the place to discuss this. You can find links to emus on gbatemp.net. You must search for yourself for BIOS files because they are illegal.

**Comment by 3dpowers** [comment]
ok

**Comment by 3dpowers** [comment]
thats confusing

**Comment by 3dpowers** [comment]
where can i find homebrews

**Comment by yellows8** [comment]
http://3dbrew.org/wiki/Homebrew_Applications See also gbafail like profi referenced above.

**Comment by 3dpowers** [comment]
is there some sort of wii to 3ds screen thing?

**Comment by yellows8** [comment]
Be more specific.

**Comment by profi200** [comment]
Again, this is not a chat. I gave you a site where you can look. Here again as link: http://gbatemp.net
And what yellows8 linked.

**Comment by 3dpowers** [comment]
like wireless screen from a wii to a 3ds that would be cool cuz i have a softmodded wii

**Comment by 3dpowers** [comment]
do you know how to install a icon pack

**Comment by yellows8** [comment]
That is not for end-users. "wireless screen ..." There's no homebrew for that.... Sounds like what Wii U already does anyway.

**Comment by 3dpowers** [comment]
SSH terminal perhaps?

**Comment by 3dpowers** [comment]
for when i need to start my minecraft server at school for some reason

**Comment by 3dpowers** [comment]
icon packs are confusing

**Comment by 3dpowers** [comment]
how to install the homescreen launcher

**Comment by yellows8** [comment]
"icon packs are confusing" That is not for end-users.

This is the wrong place for homebrew-app-requests when you can't implement it yourself.

**Comment by 3dpowers** [comment]
ok
