### ISSUE TITLE
OutDated

### ISSUE THREAD

**Issue by cl1ents** [yellows8/3ds_webkithax#5]
How can we use the browserhaxx with a outdated version ?

**Comment by yellows8** [comment]
See gbafail for that.

**Comment by cl1ents** [comment]
@yellows8 what is gbafail

**Comment by profi200** [comment]
GBAtemp aka the root of stupidnes on the internet :p

**Comment by yellows8** [comment]
https://gbatemp.net/threads/browserhax-is-still-working.400991/ etc

**Comment by cl1ents** [comment]
Only problem : I am on old3ds and it dont work

**Comment by cl1ents** [comment]
Ps : I get the error message "You need to update Your 3ds

**Comment by yellows8** [comment]
There isn't any public browser-update bypass for Old3DS at this time AFAIK.
