### ISSUE TITLE
BrowserHax Stopped Working

### ISSUE THREAD

**Issue by meleemaster101** [yellows8/3ds_webkithax#7]
I used BrowserHax to install ThemeHax. They both worked for awhile, and then suddenly neither would complete out. BrowserHax gets to the Yellow screen, and then I get an OS error message. I have tried formatting the SD card, and it didn't help. Is there any way to remedy this?

**Comment by yellows8** [comment]
"neither" Huh?

**Comment by meleemaster101** [comment]
yes, ThemeHax stopped responding to the assigned input to trigger launch (L), as well as BrowserHax doing the above.

**Comment by yellows8** [comment]
" BrowserHax gets to the Yellow screen" That's the only screen-colorfill you see right?(HTTP-download fail probably) https://github.com/yellows8/3ds_browserhax_common#homebrew-launcher

**Comment by meleemaster101** [comment]
Yes, that is the only screen-colorfill I get. What do I do?

**Comment by meleemaster101** [comment]
It just loaded through. I'm not entirely sure what changed, other than manually entering the URL instead of using the auto page.

**Comment by ghost** [comment]
Is boot.3dsx on your sd card?
